CC = g++
CPPFLAGS = -c -Wall
LDFLAGS = -lcppunit -lm
OBJ = obj/
SRC = src/
BIN = bin/
INCLUDE = inc/

all: app_get

app_get: $(OBJ)main.o $(OBJ)acc.o $(OBJ)acc.o
	$(CC) -o app_get $(OBJ)Main.o  $(OBJ)acc.o $(OBJ)acc.o
	mv app_get $(BIN) 

$(OBJ)main.o: $(SRC)main.cpp
	$(CC) $(CPPFLAGS) $(SRC)main.cpp -I $(INCLUDE)
	mv main.o $(OBJ)

$(OBJ)account.o: $(SRC)account.cpp
	$(CC) $(CPPFLAGS) $(SRC)account.cpp -I $(INCLUDE)
	mv account.o $(OBJ)



clean:
	rm -f a.out app_get *.o
	rm -f $(OBJ)*.o
	rm -f $(BIN)app_get